main: main.cpp ./CSPSolver/CSPSolver.cpp ./ConstraintGraph/ConstraintGraph.cpp ./Variable/Variable.cpp ./VariableOrderHeuristic/VariableOrderHeuristic.cpp  
	g++ main.cpp ./Variable/Variable.cpp \
	./ConstraintGraph/ConstraintGraph.cpp \
	./VariableOrderHeuristic/VariableOrderHeuristic.cpp \
	./CSPSolver/CSPSolver.cpp \
	-o main.out

clean:
	rm *.out *.o