main: main.cpp ./Variable/Variable.cpp ./Constraint/Constraint.cpp	./VariableOrderHeuristic/VariableOrderHeuristic.cpp ./CSP/CSP.cpp ./CSPSolver/CSPSolver.cpp
	g++ main.cpp ./Variable/Variable.cpp \
	./Constraint/Constraint.cpp \
	./VariableOrderHeuristic/VariableOrderHeuristic.cpp \
	./CSP/CSP.cpp \
	./CSPSolver/CSPSolver.cpp \
	-o main.out

clean:
	rm *.out *.o