main: main.cpp ./Solver/Solver.cpp ./Variable/Variable.cpp ./ConstraintGraph/ConstraintGraph.cpp ./ConstructiveHeuristic/ConstructiveHeuristic.cpp ./ConstructiveHeuristic/LargestDegreeHeuristic/LargestDegreeHeuristic.cpp ./ConstructiveHeuristic/LargestEnrollmentHeuristic/LargestEnrollmentHeuristic.cpp ./ConstructiveHeuristic/SaturationDegreeHeuristic/SaturationDegreeHeuristic.cpp ./ConstructiveHeuristic/RandomHeuristic/RandomHeuristic.cpp ./Penalty/Penalty.cpp ./PerturbativeHeuristic/PerturbativeHeuristic.cpp 
	g++ main.cpp \
	./Solver/Solver.cpp \
	./Variable/Variable.cpp \
	./ConstraintGraph/ConstraintGraph.cpp \
	./ConstructiveHeuristic/ConstructiveHeuristic.cpp \
	./ConstructiveHeuristic/LargestDegreeHeuristic/LargestDegreeHeuristic.cpp \
	./ConstructiveHeuristic/LargestEnrollmentHeuristic/LargestEnrollmentHeuristic.cpp \
	./ConstructiveHeuristic/SaturationDegreeHeuristic/SaturationDegreeHeuristic.cpp \
	./ConstructiveHeuristic/RandomHeuristic/RandomHeuristic.cpp \
	./Penalty/Penalty.cpp \
	-o main.out

clean:
	rm *.out *.o