main: main.cpp ./Solver/Solver.cpp ./Variable/Variable.cpp ./ConstraintGraph/ConstraintGraph.cpp ./Heuristic/Heuristic.cpp ./Penalty/Penalty.cpp 
	g++ main.cpp \
	./Solver/Solver.cpp \
	./Variable/Variable.cpp \
	./ConstraintGraph/ConstraintGraph.cpp \
	./Heuristic/Heuristic.cpp \
	./Penalty/Penalty.cpp \
	-o main.out

clean:
	rm *.out *.o