main: main.cpp ./Solver/Solver.cpp ./Variable/Variable.cpp ./ConstraintGraph/ConstraintGraph.cpp ./ConstructiveHeuristic/ConstructiveHeuristic.cpp ./ConstructiveHeuristic/LargestDegreeHeuristic/LargestDegreeHeuristic.cpp ./ConstructiveHeuristic/LargestEnrollmentHeuristic/LargestEnrollmentHeuristic.cpp ./ConstructiveHeuristic/SaturationDegreeHeuristic/SaturationDegreeHeuristic.cpp ./ConstructiveHeuristic/RandomHeuristic/RandomHeuristic.cpp ./KempeChain/KempeChain.cpp ./PairSwap/PairSwap.cpp ./Penalty/Penalty.cpp ./Penalty/LinearPenalty/LinearPenalty.cpp ./Penalty/ExponentialPenalty/ExponentialPenalty.cpp 
	g++ main.cpp \
	./Solver/Solver.cpp \
	./Variable/Variable.cpp \
	./ConstraintGraph/ConstraintGraph.cpp \
	./ConstructiveHeuristic/ConstructiveHeuristic.cpp \
	./ConstructiveHeuristic/LargestDegreeHeuristic/LargestDegreeHeuristic.cpp \
	./ConstructiveHeuristic/LargestEnrollmentHeuristic/LargestEnrollmentHeuristic.cpp \
	./ConstructiveHeuristic/SaturationDegreeHeuristic/SaturationDegreeHeuristic.cpp \
	./ConstructiveHeuristic/RandomHeuristic/RandomHeuristic.cpp \
	./KempeChain/KempeChain.cpp \
	./PairSwap/PairSwap.cpp \
	./Penalty/Penalty.cpp \
	./Penalty/LinearPenalty/LinearPenalty.cpp \
	./Penalty/ExponentialPenalty/ExponentialPenalty.cpp \
	-o main.out

clean:
	rm *.out *.o